services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    container_name: nginx-web
    volumes:
      - .:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles

    expose:
      - 8000
    env_file:
      - ./env/.env.dev
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/staticfiles

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/env.dev.db


volumes:
  postgres_data:
  static_volume: